import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
plot_df = pd.read_csv("MarchMadnessData/SeedPerformanceReport.csv")

def plot_seed_wins():
    plt.figure(figsize=(12, 24))
    # plt.suptitle("Games Won By Seed Over Last 16 Tournaments")

    plt.subplot(3, 2, 1)
    plt.bar(plot_df["SEED"], plot_df["R32"], label="Round of 64 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 157, 20))  
    plt.title("Round of 64 Games Won By Seed")
    plt.legend()


    plt.subplot(3, 2, 2)
    plt.bar(plot_df["SEED"], plot_df["S16"], label="Round of 32 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 140, 20))
    plt.title("Round of 32 Games Won By Seed")
    plt.legend()

    # plt.subplots_adjust(wspace=0.5)
    plt.subplot(3, 2, 3)
    plt.bar(plot_df["SEED"], plot_df["E8"], label="Sweet 16 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 111, 10))
    plt.title("Sweet 16 Games Won By Seed")
    plt.legend()

    plt.subplot(3, 2, 4)
    plt.bar(plot_df["SEED"], plot_df["F4"], label="Elite 8 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 70, 10))
    plt.title("Elite 8 Games Won By Seed")
    plt.legend()

    plt.subplot(3, 2, 5)
    plt.bar(plot_df["SEED"], plot_df["F2"], label="Final 4 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 41, 5))
    plt.title("Final 4 Games Won By Seed")
    plt.legend()

    plt.subplot(3, 2, 6)
    plt.bar(plot_df["SEED"], plot_df["CHAMP"], label="Final 2 Wins", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Games Won")
    plt.yticks(np.arange(0, 26, 5))
    plt.title("Championship Games Won By Seed")
    plt.legend()

    plt.subplots_adjust(hspace=0.8)
    plt.savefig("Figures/Seed Wins By Round.png")
    plt.show()

    plt.close()

def plot_seed_win_perc():
    plt.figure(figsize=(10, 20))
    # plt.suptitle("Games Won By Seed Over Last 16 Tournaments")

    plt.subplot(3, 2, 1)
    plt.bar(plot_df["SEED"], plot_df["R64%"], label="Round of 64 Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")  
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Round of 64 Games Win% By Seed")
    plt.legend()


    plt.subplot(3, 2, 2)
    plt.bar(plot_df["SEED"], plot_df["R32%"], label="Round of 32 Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Round of 32 Games Win% By Seed")
    plt.legend()

    # plt.subplots_adjust(wspace=0.5)
    plt.subplot(3, 2, 3)
    plt.bar(plot_df["SEED"], plot_df["S16%"], label="Sweet 16 Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Sweet 16 Games Win% By Seed")
    plt.legend()

    plt.subplot(3, 2, 4)
    plt.bar(plot_df["SEED"], plot_df["E8%"], label="Elite 8 Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Elite 8 Games Win% By Seed")
    plt.legend()

    plt.subplot(3, 2, 5)
    plt.bar(plot_df["SEED"], plot_df["F4%"], label="Final 4 Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Final 4 Games Win% By Seed")
    plt.legend()

    plt.subplot(3, 2, 6)
    plt.bar(plot_df["SEED"], plot_df["F2%"], label="Championship Win%", color="blue")
    plt.xlabel("Seed")
    plt.xticks(np.arange(1, 17, 1))
    plt.ylabel("Win%")
    plt.yticks(np.arange(0, 101, 10))
    plt.title("Championship Games Win% By Seed")
    plt.legend()

    plt.subplots_adjust(hspace=0.8)
    plt.savefig(f"Figures/Seed Win% by Round.png")
    plt.show()
    
    plt.close()


plot_seed_wins()
plot_seed_win_perc()